In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,"Aniket",3,4,5,6])
print(type(arr))
arr


<class 'numpy.ndarray'>


array(['1', '2', 'Aniket', '3', '4', '5', '6'], dtype='<U21')

### Conversion


### int to float

In [5]:
li=[1,3,5,7,9,11]
arr=np.array(li,dtype="float")
arr

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [6]:
li=[ 1.,  3.,  5.,  7.,  9., 11.]
arr=np.array(li,dtype="int")
arr

array([ 1,  3,  5,  7,  9, 11])

In [8]:
li=[1,2,3]
arr=np.array(li,dtype=complex)
arr
 

array([1.+0.j, 2.+0.j, 3.+0.j])

### float-->int


In [11]:
li=[1.1,3.3,5.5]
arr=np.array(li,dtype=int)
arr



array([1, 3, 5])

In [12]:
li=[1.1,3.3,5.5]
arr=np.array(li,dtype=complex)
arr

array([1.1+0.j, 3.3+0.j, 5.5+0.j])

### complex-->int


In [14]:
li=[1.1+0.j, 3.3+0.j, 5.5+0.j]
arr=np.array(li,dtype=int)
arr


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [16]:
li=[1.1+0.j, 3.3+0.j, 5.5+0.j]
arr=np.array(li,dtype=float)
arr

TypeError: float() argument must be a string or a real number, not 'complex'

#  Dimensions in Array:


###  1) 0-D Array:


In [34]:
arr=np.array(100)
print("Array : ",arr)
print("Dimensions of array ",arr.ndim);
print("Dimenstion f Array :",arr.shape);

Array :  100
Dimensions of array  0
Dimenstion f Array : ()


### 1) 1-D Array:


In [33]:
arr=np.array([100,300,40])
print("Array : ",arr)
print("Dimensions of array ",arr.ndim);
print("Dimenstion f Array :",arr.shape);

Array :  [100 300  40]
Dimensions of array  1
Dimenstion f Array : (3,)


### 1) 2-D Array:


In [31]:
arr=np.array([[100,200],[100,300],[1,3]])
print("Array : ",arr)
print("Dimensions of array ",arr.ndim);
print("Shape of Array ",arr.shape)

Array :  [[100 200]
 [100 300]
 [  1   3]]
Dimensions of array  2
Shape of Array  (3, 2)


### 1)` 3-D Array:


In [32]:
arr=np.array([[[100,200],[1,3],[5,6]]])
print("Array :",arr);
print("Dimenstion f Array :",arr.shape);

Array : [[[100 200]
  [  1   3]
  [  5   6]]]
Dimenstion f Array : (1, 3, 2)


In [36]:
arr=np.array([[[100,200],[1,3],[5,6]],[[3,4],[5,7],[8,9]]])
print("Array :",arr);
print("Dimenstion f Array :",arr.shape);

Array : [[[100 200]
  [  1   3]
  [  5   6]]

 [[  3   4]
  [  5   7]
  [  8   9]]]
Dimenstion f Array : (2, 3, 2)


### Indexing and Slicing:

In [39]:
arr=np.array([1,2,3,4,5])
arr[2]
 

array([[30, 40]])

In [ ]:
arr=np.array([1,2,3,4,5])
arr[1:3]


In [43]:
arr=np.array([[1,2,3,4,5,6,7,8,9,10],
             [10,20,30,40,50,60,70,80,90,100],
             [100,200,300,400,500,600,700,800,900,1000]])
arr
arr[1:2,2:5]



array([[ 30,  40],
       [300, 400]])

# NumPy Functions:


### Convert to n-D Array:


In [ ]:
arr=np.array([1,2,3])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)

In [44]:
arr=np.array([1,2,3],ndmin=2)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)

Array: [[1 2 3]]
Dimension of Array: 2
Length of Array: 1
Shape of Array: (1, 3)


In [46]:
arr=np.array([1,2,3],ndmin=3)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)

Array: [[[1 2 3]]]
Dimension of Array: 3
Length of Array: 1
Shape of Array: (1, 1, 3)


### Reshape():

In [51]:
arr=np.array([1,2,3,4])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("Length of Array:",len(arr))
print("Shape of Array:",arr.shape)
print("Reshape of Array :",arr.reshape(2,2))


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array : [[1 2]
 [3 4]]


###  1-D to 3-D Conversion using reshape:

In [55]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print("Array :",arr)
print("Dimension of array :",arr.ndim)
print("Length of Array : ",len(arr))
print("Shape of Array  : ",arr.shape)
print("Reshape of Array :",arr.reshape(1,2,5))


Array : [0 1 2 3 4 5 6 7 8 9]
Dimension of array : 1
Length of Array :  10
Shape of Array  :  (10,)
Reshape of Array : [[[0 1 2 3 4]
  [5 6 7 8 9]]]


###  Accessing elements by 'for loop':


In [57]:
arr=np.array([[1,2],[3,4]])
for i in arr:
    print("Elements in Array:",i)

for i in arr:
    for j in i:
        print("Elements in Array:",j)

Elements in Array: [1 2]
Elements in Array: [3 4]
Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


## 2) np.nditer(): The function nditer() is a helping function that can be used from very basic to very advanced iterations

In [61]:
arr=np.array([1,2,3,4])

for i in np.nditer(arr):
    print("Elements in Array:",i)


Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


### 3) np.ndenumerate(): Enumeration means mentioning  sequence number of somethings one by one

In [62]:
for i,j in enumerate(list("Hi")):
    print(i,j)

0 H
1 i


In [63]:
arr=np.array(['B','Y','E'])
for i,j in enumerate(arr):
    print(i,j)

0 B
1 Y
2 E


In [64]:
import numpy as np
arr=np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


###  4) zeros(): Return an Array with all zero elements

In [65]:
np.zeros(3,int)

array([0, 0, 0])

In [69]:
arr=np.zeros((2,3),int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

###  5) ones(): Return an array with all elements as one

In [68]:
np.ones(4,int)

array([1, 1, 1, 1])

### 6) arange(): NumPy arange() is one of the array creation routines based on numerical ranges

In [70]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [72]:
arr=np.arange(1,10,5)
arr

array([1, 6])

In [73]:
arr=np.arange(1,9,3)
arr

array([1, 4, 7])

### 7) linspace(): Returns evenly spaced values


In [81]:
arr=np.linspace(1,10,num=10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 8) eye(): It will return an array with ones on diagonal and zeros elsewhere

In [83]:

arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### identity(): Identity matrix will be returned (i.e No of Column = No of Rows)

In [84]:
arr=np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
arr=np.identity(4,3)
arr

TypeError: Cannot interpret '3' as a data type

### 10) Random: Used to generate random values of array
 • i) rand()
 • ii) randint()
 • iii) randn()
 • iv) ranf()

### i) rand(): It will return values between 0 and 1
 • Syntax:
 • np.random.rand(shape

In [86]:
arr=np.random.rand(4)
arr

array([0.61292974, 0.9385572 , 0.511972  , 0.79310657])

In [87]:
arr=np.random.rand(4,3)
arr

array([[0.48838235, 0.89251909, 0.19799764],
       [0.61746991, 0.23022748, 0.89149067],
       [0.64239082, 0.10410822, 0.62444315],
       [0.48542549, 0.41825247, 0.57854216]])

###  ii) randint(): The randint() method takes a size parameter where you can specify the shape of an array
 • Syntax:
 • np.random.randint(range,size=(value)

In [88]:
arr=np.random.randint(1,4,size=3)
arr

array([2, 2, 3], dtype=int32)

In [91]:
arr=np.random.randint(1,4,size=(3,2))
arr

array([[3, 3],
       [3, 2],
       [2, 1]], dtype=int32)

### iii) randn(): It will return values which are normally distributed
 • mean = 0 and variance = 1
 • Syntax:
 • np.random.randn(shape)

In [93]:
arr=np.random.randn(3)
arr

array([-0.15328104,  0.96549019, -1.32819934])

### ` iv) ranf(): Return values between 0 and 1


In [96]:
arr=np.random.ranf(5)
arr

array([0.9337721 , 0.27007387, 0.4936592 , 0.48212028, 0.10738511])

### 11) sort(): Sorting means putting elements in an ordered sequence
• Syntax:
 • np.sort(name)
 • axis 0--> Columns
 • axis 1--> Rows

In [106]:
arr=np.random.randint(1,10,size=5)
print("Array :",arr)
np.sort(arr)


Array : [5 5 8 2 7]


array([2, 5, 5, 7, 8], dtype=int32)

In [105]:
arr=np.random.randint(1,10,size=(5,2))
print("Array :",arr)
np.sort(arr,axis=0)


Array : [[3 4]
 [5 5]
 [1 2]
 [3 1]
 [3 6]]


array([[1, 1],
       [3, 2],
       [3, 4],
       [3, 5],
       [5, 6]], dtype=int32)

In [107]:
arr=np.random.randint(1,10,size=(5,2))
print("Array :",arr)
np.sort(arr,axis=1)

Array : [[7 1]
 [3 5]
 [4 5]
 [1 9]
 [3 9]]


array([[1, 7],
       [3, 5],
       [4, 5],
       [1, 9],
       [3, 9]], dtype=int32)

###  12) append()
 • Syntax:
 • np.append(arry1,array2,axis=None)
 • axis = 1 --> Columns
 • axis = 0 --> Rows

In [109]:
arr1=np.array([1,2,3])
arr2=np.array([4,5])
newarr=np.append(arr1,arr2,axis=None)
newarr

array([1, 2, 3, 4, 5])

### 13) ceil(): The ceil() function rounds off decimal to nearest upper integer.
 • Syntax:
 • np.ceil(value)
 • 5.1 --> 6
 • 5.9 --> 6
 • 6.5 --> 7

In [110]:
print(np.ceil(5.1))
print(np.ceil(5.9))

6.0
6.0


In [111]:
np.array(np.ceil([1.1, 2.3, 3.6, 4.9, 5.99]),int)

array([2, 3, 4, 5, 6])

### 14) floor(): The floor() function rounds off decimal to nearest lower integer.
 • Syntax:
 • np.floor()
 • 5.1--> 5
 • 5.9--> 5

In [113]:
np.array(np.floor([1.6,2.8,3.3,4.8,5.3]))

array([1, 2, 3, 4, 5])

###  15) around(): The around() function increments preceding digit or decimal by 1 if >=5 else do nothing

In [114]:
arr=np.around(2.61110,1)
arr

np.float64(2.6)

In [115]:
arr=np.around([2.61, 4.57, 6.79, 8.97])
arr

array([3., 5., 7., 9.])

In [118]:
str1="Python and Data Science"
arr=np.array(list(str1))
print(arr)
where_command=np.where(arr=="a");
print(where_command)

['P' 'y' 't' 'h' 'o' 'n' ' ' 'a' 'n' 'd' ' ' 'D' 'a' 't' 'a' ' ' 'S' 'c'
 'i' 'e' 'n' 'c' 'e']
(array([ 7, 12, 14]),)
