In [ ]:
import numpy as np

In [2]:
import numpy as np
arr=np.array([1,22,89,33])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1, 22, 89, 33])

# Change Data type


In [3]:
import numpy as np
li=[11,22,33,44]
arr=np.array(li,dtype=float)
print(arr)

[11. 22. 33. 44.]


In [4]:
import numpy as np
li=[11,22,33,44]
arr=np.array(li,dtype=complex)
print(arr)

[11.+0.j 22.+0.j 33.+0.j 44.+0.j]


In [6]:
import numpy as np
li=[11.09,22.33,33.76,44.67]
arr=np.array(li,dtype=int)
print(arr)

[11 22 33 44]


In [7]:
import numpy as np
li=[11.09,22.33,33.76,44.67]
arr=np.array(li,dtype=complex)
print(arr)

[11.09+0.j 22.33+0.j 33.76+0.j 44.67+0.j]


In [9]:
import numpy as np
li=[11.09+0.j,22.33+0.j,33.76+0.j,44.67+0.j]
arr=np.array(li,dtype=int)
print(arr)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [10]:
import numpy as np
li=[11.09+0.j,22.33+0.j,33.76+0.j,44.67+0.j]
arr=np.array(li,dtype=float)
print(arr)

TypeError: float() argument must be a string or a real number, not 'complex'

# Dimensions in Array 

### 1) 0-D Array:

In [11]:
arr=np.array(100)
print("Array:",arr)
print("Dimension of Array:",arr.ndim) 

Array: 100
Dimension of Array: 0


###  2) 1-D Array (uni-dimensional):

In [12]:
 arr=np.array([100])
 print("Array:",arr)
 print("Dimension of Array:",arr.ndim)


 arr=np.array([100],float)
 print("Array:",arr)
 print("Dimension of Array",arr.ndim)


Array: [100]
Dimension of Array: 1
Array: [100.]
Dimension of Array 1


In [14]:
arr=np.array([100,200,300])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)

Array: [100 200 300]
Dimension of Array: 1


###  3) 2-D Array:

In [16]:
arr=np.array([[1,2],[3,4],[5,6]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

Array:
[[1 2]
 [3 4]
 [5 6]]
Dimension of Array:2
Shape of Array:(3, 2)


In [19]:
arr=np.array([[1,2],[3,]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 4) 3-D Array:

In [20]:
arr=np.array([[[1,2],[3,4],[5,6]]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

Array:
[[[1 2]
  [3 4]
  [5 6]]]
Dimension of Array:3
Shape of Array:(1, 3, 2)


In [22]:
arr=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(f"Array:\n{arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Shape of Array:{arr.shape}")

Array:
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
Dimension of Array:3
Shape of Array:(2, 3, 2)


In [26]:
arr=np.array([1,2,3,4,5])
print(arr[2])


3


In [28]:
arr=np.array([1,2,3,4,5])
print(arr[1:3])


[2 3]


In [30]:

arr=np.array([[1,2,3,4,5,6,7,8,9,10],
             [10,20,30,40,50,60,70,80,90,100],
             [100,200,300,400,500,600,700,800,900,1000]])
print(arr)
print(arr[1:2,2:4])
print(arr[1:,2:4])

[[   1    2    3    4    5    6    7    8    9   10]
 [  10   20   30   40   50   60   70   80   90  100]
 [ 100  200  300  400  500  600  700  800  900 1000]]
[[30 40]]
[[ 30  40]
 [300 400]]


In [33]:
arr=np.array([[1,2,3,4,5,6,7,8,9,10],
             [10,20,30,40,50,60,70,80,90,100],
             [100,200,300,400,500,600,700,800,900,1000]])
print(arr[1:2,5:])
print(arr[0:,5:])

[[ 60  70  80  90 100]]
[[   6    7    8    9   10]
 [  60   70   80   90  100]
 [ 600  700  800  900 1000]]


#  NumPy Functions:

###  Convert to n-D Array:

In [35]:
arr=np.array([11,2,5,7,9])
print("Array :",arr)
print("Dimenstion of array :",arr.ndim)
print("Length of array :",len(arr))
print("Shape of Array  :",arr.shape)

Array : [11  2  5  7  9]
Dimenstion of array : 1
Length of array : 5
Shape of Array  : (5,)


In [37]:
arr=np.array([11,2,5,7,9],ndmin=2)
print("Array :",arr)
print("Dimenstion of array :",arr.ndim)
print("Length of array :",len(arr))
print("Shape of Array  :",arr.shape)

Array : [[11  2  5  7  9]]
Dimenstion of array : 2
Length of array : 1
Shape of Array  : (1, 5)


In [38]:
arr=np.array([11,2,5,7,9],ndmin=3)
print("Array :",arr)
print("Dimenstion of array :",arr.ndim)
print("Length of array :",len(arr))
print("Shape of Array  :",arr.shape)

Array : [[[11  2  5  7  9]]]
Dimenstion of array : 3
Length of array : 1
Shape of Array  : (1, 1, 5)


### 1) reshape(): Reshaping means changing the shape of an array

In [43]:
 import numpy as np
 arr=np.array([1,2,3,4])
 print(f"Array: {arr}")
 print(f"Dimension of Array: {arr.ndim}")
 print(f"Length of Array: {len(arr)}")
 print(f"Shape of Array: {arr.shape}")
 print(f"Reshape of Array: \n{arr.reshape(2,2)}")


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[[1 2]
 [3 4]]


In [44]:
 import numpy as np
 arr=np.array([1,2,3,4])
 print(f"Array: {arr}")
 print(f"Dimension of Array: {arr.ndim}")
 print(f"Length of Array: {len(arr)}")
 print(f"Shape of Array: {arr.shape}")
 print(f"Reshape of Array: \n{arr.reshape(4,1)}")


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[[1]
 [2]
 [3]
 [4]]


In [45]:
 import numpy as np
 arr=np.array([1,2,3,4])
 print(f"Array: {arr}")
 print(f"Dimension of Array: {arr.ndim}")
 print(f"Length of Array: {len(arr)}")
 print(f"Shape of Array: {arr.shape}")
 print(f"Reshape of Array: \n{arr.reshape(1,1,4)}")


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[[[1 2 3 4]]]


In [47]:
 import numpy as np
 arr=np.array([1,2,3,4])
 print(f"Array: {arr}")
 print(f"Dimension of Array: {arr.ndim}")
 print(f"Length of Array: {len(arr)}")
 print(f"Shape of Array: {arr.shape}")
 print(f"Reshape of Array: \n{arr.reshape(2,1,2)}")


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[[[1 2]]

 [[3 4]]]


In [48]:
 import numpy as np
 arr=np.array([1,2,3,4])
 print(f"Array: {arr}")
 print(f"Dimension of Array: {arr.ndim}")
 print(f"Length of Array: {len(arr)}")
 print(f"Shape of Array: {arr.shape}")
 print(f"Reshape of Array: \n{arr.reshape(4,)}")


Array: [1 2 3 4]
Dimension of Array: 1
Length of Array: 4
Shape of Array: (4,)
Reshape of Array: 
[1 2 3 4]


In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,0])
print(f"Array: {arr}")
print(f"Dimension of Array: {arr.ndim}")
print(f"Length of Array: {len(arr)}")
print(f"Shape of Array: {arr.shape}")
print(f"Reshape of Array: \n{arr.reshape(5,1,2)}")


Array: [1 2 3 4 5 6 7 8 9 0]
Dimension of Array: 1
Length of Array: 10
Shape of Array: (10,)
Reshape of Array: 
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]

 [[9 0]]]


###  Accessing elements by 'for loop':

In [54]:
arr=np.array([[1,2],[3,4]])
for i in arr:
    print("Element in array :",i)

Element in array : [1 2]
Element in array : [3 4]


In [56]:
arr=np.array([[1,2],[3,4]])
for i in arr:
    for j in i:
        print("Element in array :",j)

Element in array : 1
Element in array : 2
Element in array : 3
Element in array : 4


In [59]:
arr=np.array([[[1,2]],[[3,4]],[[5,6]],[[7,8]],[[9,0]]])
for i in arr:
    print("Element in array :",i)

Element in array : [[1 2]]
Element in array : [[3 4]]
Element in array : [[5 6]]
Element in array : [[7 8]]
Element in array : [[9 0]]


In [62]:
arr=np.array([[[1,2]],[[3,4]],[[5,6]],[[7,8]],[[9,0]]])
for i in arr:
    for j in i:
        print("Element in array :",j)

Element in array : [1 2]
Element in array : [3 4]
Element in array : [5 6]
Element in array : [7 8]
Element in array : [9 0]


In [63]:
arr=np.array([[[1,2]],[[3,4]],[[5,6]],[[7,8]],[[9,0]]])
for i in arr:
    for j in i:
        for k in j:
            print("Element in array :",k)

Element in array : 1
Element in array : 2
Element in array : 3
Element in array : 4
Element in array : 5
Element in array : 6
Element in array : 7
Element in array : 8
Element in array : 9
Element in array : 0


### 2) np.nditer(): The function nditer() is a helping function that can be used from very basic to very advanced iterations

In [64]:
arr=np.array([1,2,3,4])
for i in np.nditer(arr):
    print("Elements in Array:",i)

Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


In [65]:
arr=np.array([[[1,2]],[[3,4]],[[5,6]],[[7,8]],[[9,0]]])
for i in  np.nditer(arr):
    print("Element in array :",i)

Element in array : 1
Element in array : 2
Element in array : 3
Element in array : 4
Element in array : 5
Element in array : 6
Element in array : 7
Element in array : 8
Element in array : 9
Element in array : 0


### 3) np.ndenumerate(): Enumeration means mentioning sequence number of somethings one by one.

In [67]:
for i,j in enumerate(list("ANIKET")):
    print(i,j)

0 A
1 N
2 I
3 K
4 E
5 T


In [68]:
arr=np.array(['B','Y','E'])
for i,j in enumerate(arr):
    print(i,j)

0 B
1 Y
2 E


In [70]:
arr=np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


In [76]:
arr=np.array([['B','Y','E']])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) B
(0, 1) Y
(0, 2) E


### 4) zeros(): Return an Array with all zero elements

In [77]:
np.zeros(3,int)

array([0, 0, 0])

In [79]:
arr=np.zeros((2,3),int)
print(arr)

[[0 0 0]
 [0 0 0]]


### 5) ones(): Return an array with all elements as one

In [80]:
np.ones(4,int)

array([1, 1, 1, 1])

In [81]:
arr=np.ones((3,2,4),int)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


###  6) arange(): NumPy arange() is one of the array creation routines based on numerical ranges

In [82]:
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


In [84]:
arr=np.arange(2,3,4)
arr

array([2])

In [85]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr=np.arange(1,6,2)
print(arr)



[1 3 5]


###  7) linspace(): Returns evenly spaced values

In [88]:
# np.linspace(start,end,num = 50)
arr=np.linspace(1,10,num=10)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [89]:
arr=np.linspace(2,4,num=10)
arr

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

###  8) eye(): It will return an array with ones on diagonal and zeros elsewhere

In [90]:
#• np.eye(shape,dtype=int/float/complex) # by default it is float
 
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [91]:
arr=np.eye(3,2)
print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [97]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
arr=np.eye(3,dtype=complex)
arr


array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

### 9) identity(): Identity matrix will be returned (i.e No of Column = No of Rows)

In [99]:
 arr=np.identity(4)
 arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
 arr=np.identity(3,int)
 arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 10) Random: Used to generate random values of array

In [105]:
arr=np.random.rand(5)
print(arr)

[0.29981489 0.12057783 0.16262935 0.73532037 0.34708344]


In [106]:
arr=np.random.rand(3,5)
print(arr)

[[0.09523449 0.73410197 0.97378394 0.87013785 0.20761697]
 [0.56127296 0.60887859 0.45485252 0.63134702 0.08500807]
 [0.85053493 0.54299104 0.77379135 0.78441265 0.99932106]]


In [109]:
 arr=np.random.randint(1,3,size=4)
 print(arr)

[1 1 1 2]


In [110]:
 arr=np.random.randint(1,10,size=(3,5))
 print(arr)


[[4 8 7 7 2]
 [8 1 1 4 5]
 [2 1 4 9 4]]


In [111]:
 arr=np.random.randn(2,3)
 print(arr)

[[-1.41904194  0.27152764 -0.44563054]
 [ 1.0237392  -2.17061831 -1.89996541]]


In [112]:
 arr=np.random.ranf(6)
 arr

array([0.03668781, 0.81029295, 0.22257397, 0.09249749, 0.80494974,
       0.65627053])

### 11) sort(): Sorting means putting elements in an ordered sequence.

In [115]:
 arr=np.random.randint(1,10,size=5)
 print(arr)
 np.sort(arr)


[9 7 8 4 6]


array([4, 6, 7, 8, 9], dtype=int32)

In [119]:
arr=np.random.randint(1,10,size=(5,2))
print(arr)
np.sort(arr,axis=0)

[[8 2]
 [7 9]
 [5 4]
 [4 9]
 [3 1]]


array([[3, 1],
       [4, 2],
       [5, 4],
       [7, 9],
       [8, 9]], dtype=int32)

In [120]:
arr=np.random.randint(1,10,size=(5,2))
print(arr)
np.sort(arr,axis=1)

[[7 7]
 [2 2]
 [9 1]
 [3 1]
 [1 4]]


array([[7, 7],
       [2, 2],
       [1, 9],
       [1, 3],
       [1, 4]], dtype=int32)

###  12) append()

In [121]:
 arr1=np.array([1,2,3])
 arr2=np.array([4,5])
 new_arr=np.append(arr1,arr2,axis=None)
 new_arr

array([1, 2, 3, 4, 5])

In [124]:
arr1=np.array([1,2,3])
arr2=np.array([4,5])
new_arr=np.append(arr1,arr2,axis=1
                 )
new_arr


AxisError: axis 1 is out of bounds for array of dimension 1

### 13) ceil(): The ceil() function rounds off decimal to nearest upper integer.

In [125]:
print(np.ceil(5.67))

6.0


In [126]:
print(np.ceil(5.3))

6.0


In [127]:
 np.array(np.ceil([1.1, 2.3, 3.6, 4.9, 5.99]),int)

array([2, 3, 4, 5, 6])

###  14) floor(): The floor() function rounds off decimal to nearest lower integer.

In [128]:
 print(np.floor(5.1))
 print(np.floor(5.9))

5.0
5.0


In [129]:
 np.array(np.floor([1,2,3,4]),int)


array([1, 2, 3, 4])

###  15) around(): The around() function increments preceding digit or decimal by 1 if >=5 else do nothing

In [132]:
 arr=np.around(2.61110,1)
print(arr)

2.6


In [134]:
arr=np.around(np.array([2.61110,4.56789,6.7890,8.9653]),2)
print(arr)

[2.61 4.57 6.79 8.97]


###  16) where(): Return elements chosen from x or y depending on condition.

In [136]:
str1="Python and Data Science"
arr=np.array(list(str1))
print(arr)
where_command=np.where(arr=='a')
print(where_command)

['P' 'y' 't' 'h' 'o' 'n' ' ' 'a' 'n' 'd' ' ' 'D' 'a' 't' 'a' ' ' 'S' 'c'
 'i' 'e' 'n' 'c' 'e']
(array([ 7, 12, 14]),)
